name: "linter"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      # Fargate project
      - name: "fargate packages"
        run: cd fargate_task && npm clean-install
      - name: "fargate prettier"
        run: npm run prettier:check
      - name: "fargate audit"
        run: npm audit
      # Lambda project
      - name: "lambda packages"
        run: cd ../lambda && npm clean-install
      - name: "lambda prettier"
        run: npm run prettier:check
      - name: "lambda audit"
        run: npm audit
